# Generated by Django 5.1.2 on 2024-11-16 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('match_wins', models.IntegerField(default=0)),
                ('match_losses', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('AW', '2-0'), ('WN', '2-1'), ('DW', '1-1'), ('LS', '1-2'), ('AL', '0-2')], default='AW', max_length=2)),
                ('n_round', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='tournament.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='tournament.player')),
                ('tournament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='tournament.player')),
            ],
            options={
                'ordering': ('-date_played',),
            },
        ),
    ]
