# Generated by Django 5.1.2 on 2024-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_player_rivals_tournamentmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='round',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
