# Generated by Django 5.1.2 on 2024-11-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournamentmatch_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentmatch',
            old_name='round',
            new_name='n_round',
        ),
    ]
